version: "3.4"

services:
  app:
    build: .
    container_name: aj-devicesapi-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring_datasource_url: "jdbc:postgresql://db:5432/test"
      spring_jpa_database: "POSTGRESQL"
      spring_datasource_username: "amer"
      spring_datasource_password: "amer"

  db:
    image: "postgis/postgis:13-3.1-alpine"
    restart: always
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "test"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: amer
      POSTGRES_PASSWORD: amer

volumes:
  pg-data:
